### ISSUE TITLE
Multiple cards

### ISSUE THREAD

**Issue by XpressDP** [danniehansen/activity-timer#86] opened 2022-10-19 12:53 UTC
Hi there

We started using your software and discovered that if you have multiple cards you work on as soon as you start a second card time the first one's time stops.

Is this an issue or was it fixed.

**Comment by danniehansen** [comment] 2022-10-21 19:30
Hi @XpressDP,

Glade to have you. Hope you're finding use of it.

This is actually by design. The powerup does not expect a person to work on more than 1 thing at any given time. I would prefer it to continue working like this, but if we get enough people to back the wish of excluding the '1 timer per person' rule, then I could opt for making it configurable.

**Comment by XpressDP** [comment] 2022-10-24 05:14
Hi there

ok tx for the feedback. It works great but unfortunately we run a print shop and one person can work over a couple of printers at the same time so in essence they can work on a couple of jobs at the same time. So the software wont work for us. Tx

**Comment by danniehansen** [comment] 2024-01-08 22:04
Closing for now as there was not enough support for this feature 👍

**Closed by danniehansen** 2024-01-08 22:04 UTC
Labels: enhancement
