### ISSUE TITLE
"Activity timer history" does not load / Stuck in loading.

### ISSUE THREAD

**Issue by Feardrop** [danniehansen/activity-timer#15] opened 2020-08-31 07:55 UTC
The popup window "Activity timer history" does not display any content anymore (after the new update 1.1.0), except a rotating loading circle.

I tested this in Firefox and Edge, neither works.

![grafik](https://user-images.githubusercontent.com/28101114/91696409-d07d6f00-eb6f-11ea-8979-0457fa2f1893.png)

----
**Edit:**
Apparently the token for this request is invalid: 
`const data = await fetch('https://api.trello.com/1/boards/' + board.id + '/cards/all?pluginData=true&fields=id,name,labels,pluginData,closed&key=' + apiKey + '&token=' + token + '&r=' + new Date().getTime());`. 
According to the browser code-analysis the answer to the request is `invalid token`.

Thus the JSON-Parser throws an `Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` error.

IMHO there is an issue with the aquiring of the token. Maybe force a reset after update.

**Comment by danniehansen** [comment] 2020-08-31 16:01
Good observation. Thank you for the detailed bug report, much appreciated! I'll be looking into the issue this evening or tomorrow. Once again, thank you :)

**Comment by Feardrop** [comment] 2020-08-31 16:15
Of course, mate. ;-)
And thank you for this nice plugin!

Greetings, Norman

Am 31.08.2020 um 18:01 schrieb Dannie Hansen <notifications@github.com>:

﻿

Good observation. Thank you for the detailed bug report, much appreciated! I'll be looking into the issue this evening or tomorrow. Once again, thank you :)

**Comment by danniehansen** [comment] 2020-09-01 18:00
@Feardrop It should be fixed now. Pushed a new hotfix for this. Activity timer will now fall back to showing authentication screen in case any exception occurs during network transfer for getting the activity timer history records.

Thanks for reporting this issue. If the issue persist please try to flush browser cache and try again.

**Comment by Feardrop** [comment] 2020-09-02 07:02
@danniehansen The initial catch works. I can see the "Activate" text and button. But the authentication screen popup window opens and closes immediately. The algorithm tries to fetch the history-data with the original token. Therefore it gets an `invalid token` response and crashes. 

I cleared my browser and even used a different one.
i don't know where the token value is stored, but i think you should assert that after the "activation" procedure the token has changed and that a new token is used.

**Comment by danniehansen** [comment] 2020-09-02 11:21
Ouch. My bad. Was unable to reproduce an invalid token to test, so I made
an assumption. I'll investigate further tonight. Thank you for your
patience :)

**Comment by danniehansen** [comment] 2020-09-02 19:15
@Feardrop Looks like GitHub automatically closes the issue when i merge a merge request connected to it... annoying. However - i think i found the issue. When token becomes invalid or otherwise no longer work it will keep responding with the same token when you make new authentication requests. I had to manually force revoke existing token before re-authenticating again.

My test wen't well. But I'm not sure of how it plays out in the wild. Could you try again? & if issue persist with a cleared cache?

**Comment by danniehansen** [comment] 2020-09-03 17:56
@Feardrop Glad to hear! Thanks once again for reporting this :)

**Closed by danniehansen** 2020-09-03 17:56 UTC
Labels: bug
