### ISSUE TITLE
Auto-start feature stops unwanted

### ISSUE THREAD

**Issue by AnonymousDuck123** [danniehansen/activity-timer#130] opened 2023-12-12 08:31 UTC
Hi Dannie,

First of all, what an amazing PowerUp! I have been using it for several years now and it helps me to be more satisfied at work because I know what I am spending my time on and I am more productive. So: THANK YOU!

Unfortunately, for the past few weeks, maybe even months, I have had a problem with the auto-start feature. It usually starts when I drag the card to 'Do', but lately it seems to stop automatically. I have not been able to identify any pattern so far. Most of the time it just starts when I drag the card to Doing, but when I look back in Trello a few minutes later, the timer has stopped at 0 or 1 minute. Other times it does not start at all or takes longer than usual to start. I have also tried opening the card and starting the timer there, but the same problem occurs. 

I am using Trello as an application on Windows 10. Do you have any idea what this could be? And if I can be of any help in troubleshooting, please let me know.

Kind regards
Hendrik

**Comment by danniehansen** [comment] 2023-12-14 20:20
Hi @AnonymousDuck123,

Thank you. Glad you like it :)

I'll look into this issue this weekend. Thank you for reporting it.

**Comment by danniehansen** [comment] 2023-12-22 16:29
Hi @AnonymousDuck123 ,

My apologies for not getting back earlier. The holidays is causing my time to be limited and haven't yet had the time that i was planning to look into this. I'll look into it as soon as possible.

Happy holidays :)

**Comment by AnonymousDuck123** [comment] 2024-01-02 09:36
Hi @danniehansen .

No worries and take all the time you need. Family, friends and other personal topics go first :) 

In the mean time, it appears that there is at least some reproducibility of the issue. Most of the times, when I have pulled the ticket into the "Doing" list, it starts and works well. I then work on other things and have the Trello app window in the background. But when I select the Trello app window to be in the foreground again, the timer stops. This is to my understanding not the intended function since I often simply want to take notes in another ticket. It also does not explain, why the timer sometimes stops when I was in the Trello App window the whole time but maybe it helps you to better identify the issue.

Happy holidays :)

**Comment by danniehansen** [comment] 2024-01-08 21:58
@AnonymousDuck123 Thank you. Appreciate the patience.

I'm wondering if this may be similar case as https://github.com/danniehansen/activity-timer/issues/134

Have the card moved since you minimized the trello app? There is a setting to automatically stop the timer upon moving the card. The tick which checks for this will run immediately when you re-open it and then it would appear as if re-opening it triggered it.

Could you try and disable this setting to see if it may be it causing it? And if it is, could there be others moving the card or could you be moving it in another window?

**Comment by AnonymousDuck123** [comment] 2024-01-09 08:17
It seems similar, but different. I work on the board alone, so nobody is moving the cards. 

Most of the time, it is also the first timer being set on the board, so no working on a ticket several times. 

These are my settings: ![1](https://github.com/danniehansen/activity-timer/assets/153600030/1dca3d8f-4be0-4980-846f-9c080836b430)

**Comment by danniehansen** [comment] 2024-01-09 22:23
@AnonymousDuck123  could you try the new 2.4.3 version? You can confirm if you're on this version by opening the activity timer board button.

I found a way to reproduce the problem all the time and managed to fix it. It was related to auto-stop functionality causing it to automatically stop on the next tick.

**Comment by AnonymousDuck123** [comment] 2024-01-10 08:19
That seems to have fixed it! Looks good so far *party* (And I assume you mean version 2.7.3 :) )

Thank you a lot for all your efforts!

**Comment by danniehansen** [comment] 2024-01-10 19:22
@AnonymousDuck123 Perfect. Glad to hear. No problem at all :)

**Closed by danniehansen** 2024-01-10 19:22 UTC
Labels: bug
