### ISSUE TITLE
Estimate accepts only entire hours

### ISSUE THREAD

**Issue by Qterion** [danniehansen/activity-timer#131] opened 2023-12-14 11:42 UTC
Hey Dianne,

First of all, big thanks for the plugin! I've been using the PowerUp "Activity Timer," and it's been handy. But there's a hiccup in version 2.7.1 - can't input decimals right in the "Estimate" field. Like, when I try 0,5, it thinks it's 5 hours and 30 minutes.

Mind checking it out? Let me know if you need more info.

Thanks again!
![image-20231212-165443](https://github.com/danniehansen/activity-timer/assets/60145661/4983fafa-000d-4026-b05d-2abab7ba361d)
![image-20231212-165537](https://github.com/danniehansen/activity-timer/assets/60145661/1a4c0432-746d-41d0-87ef-179b1d855b4e)

**Comment by danniehansen** [comment] 2023-12-14 20:21
Hi @Qterion,

I'll check this out this weekend. Thank you for reporting it.

**Comment by danniehansen** [comment] 2023-12-22 16:29
Hi @Qterion,

My apologies for not getting back earlier. The holidays is causing my time to be limited and haven't yet had the time that i was planning to look into this. I'll look into it as soon as possible.

Happy holidays :)

**Comment by MoritzKrohn** [comment] 2024-01-22 12:50
I'd like to +1 this issue. Can't estimate anything but whole hours, either.

Otherwise this is a great power-up. Thanks for making it :) !

**Comment by danniehansen** [comment] 2024-01-25 21:29
Sorry @MoritzKrohn & @Qterion for not getting back on this. Christmas and the past weeks has been tanking on my time.

I'll try to prioritize this as soon as possible to get it resolved 👍

**Comment by MoritzKrohn** [comment] 2024-01-28 10:49
Ah, now worries & no hurry! I'm grateful that you've made this little tool and give it away for free. Thanks again for you efforts!

**Comment by danniehansen** [comment] 2024-01-28 17:56
@MoritzKrohn & @Qterion 

I've checked the current live version and decimals are working fine here. I think the problem may be that you're attempting to use **,** as a decimal indicator and not **.**

Works: 5.5
Doesn't work: 5,5

If you use . as a separator it should work just fine 👍

**Comment by MoritzKrohn** [comment] 2024-01-29 08:41
@danniehansen No, I'm sorry, but that's not it. I tried a lot of things, including different decimal indicators, but also typing the estimate in another text editor and then copy pasting the value. Nothing worked so far!

I'd love to provide you a gif to illustrate the problem, but the "estimate" input-field doesn't even react to the typing of a period (.) so there's nothing to record. There's simply nothing happening.

Staying with your example of 5.5 hours:

a) If I type `5` followed by `.` followed by `5` again, the estimate shows 55h, because the `.` is not registered at all. 

b) If I type `5` followed by `,` the comma shows, so we now have `5,`. But as soon as I press `5` the second time to hopefully get to "5,5", the input field now weirdly shows `5.5,5`. And as soon as I press Enter or click outside the input field, the estimate now is 55:30h.

There's just no way to input a decimal, at least for me and Qterion, apparently. I'm not sure if this could have to do with me being on MacOS, but everything else related to Trello and Activity Timer works just fine.

Here's a gif showcasing the two examples, a) and b). You can't see what I'm typing, unfortunately, but the first time it is a period which is not showing, and the second time it's a comma which leads to a weird result.

![estimate-problems](https://github.com/danniehansen/activity-timer/assets/13201518/5a8fca0a-bc1b-4e58-b171-b2dcfeb2e8cb)

**Comment by danniehansen** [comment] 2024-02-06 18:36
@MoritzKrohn Thank you for the detailed reply!

That is strange indeed. I'm suspecting it may be to localization differences with the field. I'll look into this 👍 

Appreciate the detailed reporting 🙏

**Comment by danniehansen** [comment] 2024-03-12 21:34
@MoritzKrohn @Qterion My apologies for the extended delay on getting this resolved. I was finally able to reproduce this in Firefox and traced it to locale configurations for the input field.

I've changed it to en-GB in https://github.com/danniehansen/activity-timer/releases/tag/2.7.5 and this appears to resolve the problem in Firefox and align both Safari, Firefox, Edge and Chrome.

Can you check to see if this resolves your problem? Please also if it persist confirm if you're running 2.7.5 in the board button 👍

**Comment by MoritzKrohn** [comment] 2024-03-22 20:15
@danniehansen  My apologies! I only today caught up on e-mails. Yes, amazing, it works now :)) ! Thanks a lot!!

**Comment by danniehansen** [comment] 2024-03-25 21:37
No worries at all :) Glad it worked. Closing 👍

**Closed by danniehansen** 2024-03-25 21:37 UTC
