### ISSUE TITLE
Add 24-hour format support

### ISSUE THREAD

**Issue by ludwig801** [danniehansen/activity-timer#72] opened 2022-05-05 09:51 UTC
Hello.

Being from an european country, I find it extremely confusing to insert/edit timestamps in the current 12-hour (AM/PM).
It would be great if you could make available some sort of configuration so as to be able to enable 24-hour format in "manage time" timestamps.

---

PS: I love the power-up, keep up the good work!

**Comment by danniehansen** [comment] 2022-05-11 19:09
Hi @ludwig801,

The issue is that Trello's datetime picker that is official doesn't appear to support 24-hour format. I could however create my own and replace it. I'll keep this open and next time I get some time to work on Activity timer I'll look into supporting this. Appreciate the feedback! And glad that you like it 💯

**Comment by danniehansen** [comment] 2022-07-22 20:18
Adding it to next milestone. Will see if I can get to it & include this.

**Comment by danniehansen** [comment] 2022-08-11 20:42
@ludwig801  Sorry for the delay. It's now been released with https://github.com/danniehansen/activity-timer/releases/tag/2.2.0

Decided to change over to 24hr instead of 12hr. Much broader audience for who uses the powerup. Will be adding 12hr support by configuration at a later point. Please let me know what you think of the latest release & how it works.

**Closed by danniehansen** 2022-08-11 20:42 UTC
Labels: enhancement
